### ISSUE TITLE
Extract function causes problems

### ISSUE THREAD

**Issue by vojtaiii** [ishipachev/biosignal_challenge_2020#1]
Hi,
I`ve been running into problems when testing your algorithm on some of our data. 
It seems your are using function _extract_ from a given toolbox but my desktop is unaware of it. 
In particular, running _articulation_rate_ displays message

`Undefined function 'extract' for input arguments of type 'double'.`

My desktop is picking extract _function_ from here:

`which extract`

`C:\Program Files\MATLAB\R2019_a\toolbox\slcoverage\@cvdata\extract.m  % cvdata method`

and I think thats not the one your are using. 
Can you please specify the origin of _extract_? 

Thanks
Vojta

**Comment by ishipachev** [comment]
Hi @vojtaiii,

This function belongs to Audio Toolbox:
`>> which extract
F:\programs\Matlab2020a\toolbox\audio\audio\audioFeatureExtractor.m  % audioFeatureExtractor method`

I've also fixed couple erros in _articulation_rate.m_
And hope today will finish already started for _splitLabeledData.m_ to make it easier to point out which data should be used for training.

**Comment by ishipachev** [comment]
I've reworked usage of labeled data and its splitting on train and validation dataset. Should be easier to use on different data now.
